---
# Selinux のモード変更
- name: configure / Selinux permissived
  selinux:
    state: disabled
  when : ansible_selinux.status != 'disabled'

# Firewalld の無効化
- name: Firewalld stopped
  service:
    name: firewalld
    state: stopped

# ロケールの設定
- name: main / Setup timezone
  timezone:
    name: "Asia/Tokyo"

- name: main / Setup locale
  command: localectl set-locale LANG=ja_JP.utf8
  register: changed_result
  changed_when: changed_result.rc != 0  # rc : 実行結果失敗時に0以外がア入る

# EPEL リポジトリの設定
- name: configure / Import EPEL Repository
  yum:
    name: epel-release
    state: latest
    update_cache: yes

# yum パッケージのインストール
- name: be sure wget and vim is installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - vim
    - patch
    - gcc
    - gcc-c++
    - tree
    - unzip
...